export const GET_ADMINS_PENDING = 'GET_ADMINS_PENDING';
export const GET_ADMINS_FULFILLED = 'GET_ADMINS_FULFILLED';
export const GET_ADMINS_REJECTED = 'GET_ADMINS_REJECTED';
export const DELETE_ADMINS_PENDING = 'DELETE_ADMINS_PENDING';
export const DELETE_ADMINS_FULFILLED = 'DELETE_ADMINS_FULFILLED';
export const DELETE_ADMINS_REJECTED = 'DELETE_ADMINS_REJECTED';
