export const GET_EMPLOYEES_PENDING = 'GET_EMPLOYEES_PENDING';
export const GET_EMPLOYEES_FULFILLED = 'GET_EMPLOYEES_FULFILLED';
export const GET_EMPLOYEES_REJECTED = 'GET_EMPLOYEES_REJECTED';
export const DELETE_EMPLOYEES_PENDING = 'DELETE_EMPLOYEES_PENDING';
export const DELETE_EMPLOYEES_FULFILLED = 'DELETE_EMPLOYEES_FULFILLED';
export const DELETE_EMPLOYEES_REJECTED = 'DELETE_EMPLOYEES_REJECTED';
