export const GET_TASKS_PENDING = 'GET_TASKS_PENDING';
export const GET_TASKS_FULFILLED = 'GET_TASKS_FULFILLED';
export const GET_TASKS_REJECTED = 'GET_TASKS_REJECTED';

export const DELETE_TASKS_PENDING = 'DELETE_TASKS_PENDING';
export const DELETE_TASKS_FULFILLED = 'DELETE_TASKS_FULFILLED';
export const DELETE_TASKS_REJECTED = 'DELETE_TASKS_REJECTED';

export const POST_TASKS_PENDING = 'POST_TASKS_PENDING';
export const POST_TASKS_FULFILLED = 'POST_TASKS_FULFILLED';
export const POST_TASKS_REJECTED = 'POST_TASKS_REJECTED';
