export const GET_TIMESHEETS_PENDING = 'GET_TIMESHEETS_PENDING';
export const GET_TIMESHEETS_FULFILLED = 'GET_TIMESHEETS_FULFILLED';
export const GET_TIMESHEETS_REJECTED = 'GET_TIMESHEETS_REJECTED';

export const DELETE_TIMESHEETS_PENDING = 'DELETE_TIMESHEETS_PENDING';
export const DELETE_TIMESHEETS_FULFILLED = 'DELETE_TIMESHEETS_FULFILLED';
export const DELETE_TIMESHEETS_REJECTED = 'DELETE_TIMESHEETS_REJECTED';

export const POST_TIMESHEETS_PENDING = 'POST_TIMESHEETS_PENDING';
export const POST_TIMESHEETS_FULFILLED = 'POST_TIMESHEETS_FULFILLED';
export const POST_TIMESHEETS_REJECTED = 'POST_TIMESHEETS_REJECTED';

export const PUT_TIMESHEETS_PENDING = 'PUT_TIMESHEETS_PENDING';
export const PUT_TIMESHEETS_FULFILLED = 'PUT_TIMESHEETS_FULFILLED';
export const PUT_TIMESHEETS_REJECTED = 'PUT_TIMESHEETS_REJECTED';

export const GETBYID_TIMESHEETS_PENDING = 'GETBYID_TIMESHEETS_PENDING';
export const GETBYID_TIMESHEETS_FULFILLED = 'GETBYID_TIMESHEETS_FULFILLED';
export const GETBYID_TIMESHEETS_REJECTED = 'GETBYID_TIMESHEETS_REJECTED';
