export const GET_PROJECTS_PENDING = 'GET_PROJECTS_PENDING';
export const GET_PROJECTS_FULFILLED = 'GET_PROJECTS_FULFILLED';
export const GET_PROJECTS_REJECTED = 'GET_PROJECTS_REJECTED';
export const POST_PROJECTS_PENDING = 'POST_PROJECTS_PENDING';
export const POST_PROJECTS_FULFILLED = 'POST_PROJECTS_FULFILLED';
export const POST_PROJECTS_REJECTED = 'POST_PROJECTS_REJECTED';
